// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/rules": {
    params: {};
  };
  "/cards": {
    params: {};
  };
  "/decks": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/rules" | "/cards" | "/decks" | "/faq" | "/contact";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/rules" | "/cards" | "/decks" | "/faq" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/rules.tsx": {
    id: "routes/rules";
    page: "/rules";
  };
  "routes/cards.tsx": {
    id: "routes/cards";
    page: "/cards";
  };
  "routes/decks.tsx": {
    id: "routes/decks";
    page: "/decks";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/rules": typeof import("./app/routes/rules.tsx");
  "routes/cards": typeof import("./app/routes/cards.tsx");
  "routes/decks": typeof import("./app/routes/decks.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};